In [15]:
import pandas as pd

In [16]:
d1

,Instancia,Plantas,Produtos,Periodos,Lower Bound (LB),Upper Bound (UB),Gap,Tempo (s),Status
0,AAA01226_0,2,6,12,40524.18,40524.18,0.00,7.06,2
1,AAA01226_1,2,6,12,40481.74,40481.74,0.00,15.34,2
2,AAA01226_2,2,6,12,46248.15,46248.15,0.00,27.24,2
3,AAA01226_3,2,6,12,45679.36,45679.36,0.00,586.50,2
4,AAA01226_4,2,6,12,38339.65,38339.65,0.00,39.19,2
...,...,...,...,...,...,...,...,...,...
175,AAB0122090_0,20,90,12,3803089.92,6462431.73,0.41,1800.15,9
176,AAB0122090_1,20,90,12,3760058.00,9069179.82,0.59,1800.14,9
177,AAB0122090_2,20,90,12,3807447.13,6266452.78,0.39,1800.12,9
178,AAB0122090_3,20,90,12,3771044.94,5991566.55,0.37,1800.13,9
179,AAB0122090_4,20,90,12,3741698.49,9034272.99,0.59,1800.12,9

In [17]:
d1 = pd.read_csv('../solve_gurobi/resultados1.csv')
d2 = pd.read_csv('../solve_gurobi/resultados2.csv')
d3 = pd.read_csv('../solve_gurobi/resultados3.csv')
d4 = pd.read_csv('../solve_gurobi/resultados4.csv')

In [18]:
df_combined = pd.concat([d1, d2, d3, d4])
filtered_df = df_combined[['Instancia', 'Lower Bound (LB)', 'Upper Bound (UB)', 'Gap', 'Tempo (s)', 'Plantas', 'Produtos']]

In [19]:
filtered_df.to_csv('resultados_gurobi_completo.csv', index=False)